// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const ACRONYMS = new Set(['AI', 'AIDLC', 'AGUI', 'API', 'ARB', 'AWS', 'CTO', 'DPDP', 'EA', 'EU', 'IAC', 'IBM', 'MCP', 'OKR', 'RAG', 'SOC', 'TOGAF', 'UI', 'UX']);

function sidebarLabel(id) {
  const basename = id.split('/').at(-1)
    .replace(/^(\d+)[_-]/, '$1 ')
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replace(/[_-]+/g, ' ');
  return basename.split(/\s+/).map((word) => {
    const upper = word.toUpperCase();
    if (ACRONYMS.has(upper) || /^\d/.test(word)) return upper;
    return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
  }).join(' ');
}

// Index pages get a section-specific label ("AI Economics Overview" rather than a
// bare "Overview") so they stay distinguishable in search results and long sidebars.
function overviewLabel(id) {
  const section = id.split('/').at(-2);
  return section ? `${sidebarLabel(section)} Overview` : 'Overview';
}

function isIndexDoc(item) {
  return item.type === 'doc' && typeof item.id === 'string' && item.id.endsWith('/index');
}

function normalizeItems(items, topLevel = false) {
  const normalized = items.map((item) => {
    if (typeof item === 'string') {
      return {type: 'doc', id: item, label: item.endsWith('/index') ? overviewLabel(item) : sidebarLabel(item)};
    }
    if (item.type === 'category') return {...item, items: normalizeItems(item.items)};
    return item;
  });
  return normalized.sort((left, right) => {
    if (topLevel && left.label === 'Home') return -1;
    if (topLevel && right.label === 'Home') return 1;
    if (topLevel && left.label === 'About') return 1;
    if (topLevel && right.label === 'About') return -1;
    if (isIndexDoc(left) && !isIndexDoc(right)) return -1;
    if (isIndexDoc(right) && !isIndexDoc(left)) return 1;
    return (left.label ?? '').localeCompare(right.label ?? '', undefined, {numeric: true, sensitivity: 'base'});
  });
}

const sidebars = {
  tutorialSidebar: normalizeItems([
    {type: 'doc', id: 'index', label: 'Home'},
    {
      type: 'category',
      label: 'Multimodal AI',
      items: [
        'multimodal-ai/index',
        {type: 'doc', id: 'multimodal-ai/part-01-foundations', label: 'Part 1 — Foundations: VLMs, ALMs, Tokenization & Models'},
        {type: 'doc', id: 'multimodal-ai/part-02-enterprise-architecture', label: 'Part 2 — Enterprise Architecture & Agent Taxonomy'},
        {type: 'doc', id: 'multimodal-ai/part-03-modalities-image-document', label: 'Part 3 — Image & Document Intelligence'},
        {type: 'doc', id: 'multimodal-ai/part-04-modalities-video-audio', label: 'Part 4 — Video & Audio Intelligence'},
        {type: 'doc', id: 'multimodal-ai/part-05-multimodal-rag', label: 'Part 5 — Multimodal RAG'},
        {type: 'doc', id: 'multimodal-ai/part-06-agentic-workflows', label: 'Part 6 — Agentic Workflows'},
        {type: 'doc', id: 'multimodal-ai/part-07-security-threats', label: 'Part 7 — Security & Threat Taxonomy'},
        {type: 'doc', id: 'multimodal-ai/part-08-guardrails-sanitization', label: 'Part 8 — Guardrails & Sanitization'},
        {type: 'doc', id: 'multimodal-ai/part-09-compliance-responsible-ai', label: 'Part 9 — Compliance & Responsible AI'},
        {type: 'doc', id: 'multimodal-ai/part-10-evaluation-benchmarks', label: 'Part 10 — Evaluation & Benchmarks'},
        {type: 'doc', id: 'multimodal-ai/part-11-evaluation-harnesses-cicd', label: 'Part 11 — Evaluation Harnesses & CI/CD'},
        {type: 'doc', id: 'multimodal-ai/part-12-observability-finops', label: 'Part 12 — Observability & FinOps'},
        {type: 'doc', id: 'multimodal-ai/part-13-governance-production', label: 'Part 13 — Governance & Production Engineering'},
        {type: 'doc', id: 'multimodal-ai/part-14-cloud-platform-comparison', label: 'Part 14 — Cloud Platform Comparison'},
        {type: 'doc', id: 'multimodal-ai/part-15-emerging-trends-bibliography', label: 'Part 15 — Emerging Trends & Bibliography'},
      ],
    },
    {
      type: 'category',
      label: 'Databricks Agentic AI',
      items: [
        'databricks-agentic-ai/index',
        {type: 'doc', id: 'databricks-agentic-ai/part-01-platform-vision-agentic-services', label: 'Part 1 — Platform Vision & Agentic Services'},
        {type: 'doc', id: 'databricks-agentic-ai/part-02-agent-lake-architecture', label: 'Part 2 — Agent Lake, Architecture & Multi-Agent'},
        {type: 'doc', id: 'databricks-agentic-ai/part-03-mosaic-ai-mlflow', label: 'Part 3 — Mosaic AI & MLflow 3'},
        {type: 'doc', id: 'databricks-agentic-ai/part-04-unity-catalog-governance', label: 'Part 4 — Unity Catalog AI Governance'},
        {type: 'doc', id: 'databricks-agentic-ai/part-05-lakehouse-data-infrastructure', label: 'Part 5 — Lakebase, LTAP & Lakehouse RT'},
        {type: 'doc', id: 'databricks-agentic-ai/part-06-iceberg-open-formats', label: 'Part 6 — Apache Iceberg & Open Table Formats'},
        {type: 'doc', id: 'databricks-agentic-ai/part-07-security-architecture', label: 'Part 7 — Security Architecture'},
        {type: 'doc', id: 'databricks-agentic-ai/part-08-observability-finops-integration', label: 'Part 8 — Observability, FinOps & Integrations'},
        {type: 'doc', id: 'databricks-agentic-ai/part-09-competitive-reference-architectures', label: 'Part 9 — Competitive Comparison & Reference Architectures'},
        {type: 'doc', id: 'databricks-agentic-ai/part-12-finops', label: 'Part 12 — FinOps & Cost Engineering'},
        {type: 'doc', id: 'databricks-agentic-ai/part-13-vendor-landscape', label: 'Part 13 — Vendor Landscape'},
      ],
    },
    {
      type: 'category',
      label: 'Enterprise Strategy & Business Architecture',
      items: [
        'enterprise-strategy/index',
        {type: 'doc', id: 'enterprise-strategy/vol1-corporate-strategy', label: 'Vol 1 — Corporate Strategy'},
        {type: 'doc', id: 'enterprise-strategy/vol2-business-architecture-operating-model', label: 'Vol 2 — Business Architecture & Operating Models'},
        {type: 'doc', id: 'enterprise-strategy/vol3-portfolio-governance', label: 'Vol 3 — Portfolio Management & Governance'},
        {type: 'doc', id: 'enterprise-strategy/vol4-consulting-frameworks-industry', label: 'Vol 4 — Consulting Frameworks & Industry Strategy'},
        {type: 'doc', id: 'enterprise-strategy/vol5-ai-strategy-transformation-glossary', label: 'Vol 5 — AI Strategy, Transformation & Glossary'},
        {type: 'doc', id: 'enterprise-strategy/vol6-organization-structure-operating-model', label: 'Vol 6 — Organization Structure & Operating Model'},
        {type: 'doc', id: 'enterprise-strategy/vol7-enterprise-building-blocks', label: 'Vol 7 — Enterprise Building Blocks'},
        {type: 'doc', id: 'enterprise-strategy/vol8-portfolio-consulting-frameworks', label: 'Vol 8 — Portfolio & Consulting Frameworks'},
        {type: 'doc', id: 'enterprise-strategy/vol9-industry-deep-dives', label: 'Vol 9 — Industry Strategy Deep Dives'},
        {type: 'doc', id: 'enterprise-strategy/vol10-relationship-maps-glossary', label: 'Vol 10 — Relationship Maps & Glossary'},
      ],
    },
    {
      type: 'category',
      label: 'Enterprise AI Research Report',
      items: [
        'enterprise-ai-report/index',
        'enterprise-ai-report/part-01-evolution',
        'enterprise-ai-report/part-02-operating-models',
        'enterprise-ai-report/part-03-ai-delivery-lifecycle',
        'enterprise-ai-report/part-04-genai-delivery',
        'enterprise-ai-report/part-05-agentic-lifecycle',
        'enterprise-ai-report/part-06-governance',
        'enterprise-ai-report/part-07-platform-operating-model',
        'enterprise-ai-report/part-08-organizational-roles',
        'enterprise-ai-report/part-09-operating-processes',
        'enterprise-ai-report/part-10-service-catalog',
        'enterprise-ai-report/part-11-devsecops',
        'enterprise-ai-report/part-12-responsible-ai',
        'enterprise-ai-report/part-13-security-model',
        'enterprise-ai-report/part-14-observability',
        'enterprise-ai-report/part-15-enterprise-architecture',
        'enterprise-ai-report/part-16-financial-model',
        'enterprise-ai-report/part-17-transformation-roadmap',
        'enterprise-ai-report/part-18-case-studies',
        'enterprise-ai-report/part-19-deliverables',
        'enterprise-ai-report/part-20-greenfield-vs-brownfield',
        'enterprise-ai-report/part-21-agentic-process-blueprint',
      ],
    },
    {
      type: 'category',
      label: 'Agentic AI',
      items: [
        'agentic-systems/index',
        {
          type: 'category',
          label: 'Platform',
          items: [
            'agentic-systems/platform/index',
            'agentic-systems/platform/MultiTenantAgentPlatform_Architecture',
            'agentic-systems/platform/agentic_platform_bestpractices',
            'agentic-systems/platform/ai-platform-factory-runbook-v2',
            'agentic-systems/platform/ai-msf-requirements-runbook',
            'agentic-systems/platform/enterprise-agentic-ai-asset-management-2026',
            'agentic-systems/platform/genaiaf-prompt-lifecycle-hotswap-research-2026',
            'agentic-systems/platform/Enterprise_PromptOps_AWS_AgentCore_2026',
          ],
        },
        {
          type: 'category',
          label: 'Memory',
          items: [
            'agentic-systems/memory/index',
            'agentic-systems/memory/AI_Memory_Agent_Innovations_Research_Report',
          ],
        },
        {
          type: 'category',
          label: 'Agent Skills',
          items: [
            'agentic-systems/skill/index',
            'agentic-systems/skill/00-executive-summary-and-reference-architecture',
            'agentic-systems/skill/Agent_Skills_Complete_Playbook_2026',
            {
              type: 'category',
              label: 'Enterprise Platform Research',
              items: [
                'agentic-systems/skill/enterprise/index',
                'agentic-systems/skill/enterprise/01-foundations-what-is-an-agent-skill',
                'agentic-systems/skill/enterprise/02-skill-anatomy-and-metadata-schema',
                'agentic-systems/skill/enterprise/03-execution-lifecycle-and-tracing',
                'agentic-systems/skill/enterprise/04-skills-tools-mcp-a2a-relationship',
                'agentic-systems/skill/enterprise/05-tool-definition-best-practices',
                'agentic-systems/skill/enterprise/06-registry-discovery-and-deduplication',
                'agentic-systems/skill/enterprise/07-composition-and-instructions-engineering',
                'agentic-systems/skill/enterprise/08-observability-and-evaluation',
                'agentic-systems/skill/enterprise/09-security-architecture',
                'agentic-systems/skill/enterprise/10-governance-and-lifecycle',
                'agentic-systems/skill/enterprise/11-architecture-patterns-antipatterns-and-case-studies',
              ],
            },
            'agentic-systems/skill/a2a_deep_research',
            {
              type: 'category',
              label: 'Coding Assistant Research',
              items: [
                'agentic-systems/skill/coding/index',
                'agentic-systems/skill/coding/01-foundations-what-is-a-coding-skill',
                'agentic-systems/skill/coding/02-skill-anatomy-and-metadata-schema',
                'agentic-systems/skill/coding/03-discovery-and-execution-lifecycle',
                'agentic-systems/skill/coding/04-skills-tools-mcp-relationship',
                'agentic-systems/skill/coding/05-tool-definitions-and-instructions-engineering',
                'agentic-systems/skill/coding/06-repository-context-engineering',
                'agentic-systems/skill/coding/07-vscode-devcontainers-integration',
                'agentic-systems/skill/coding/08-mcp-integration-and-memory',
                'agentic-systems/skill/coding/09-multi-agent-and-observability',
                'agentic-systems/skill/coding/10-governance-and-security',
                'agentic-systems/skill/coding/11-evaluation-reusability-deduplication',
                'agentic-systems/skill/coding/12-enterprise-workflows-comparative-analysis-and-patterns',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Configuration',
          items: [
            'agentic-systems/config/index',
            'agentic-systems/config/enterprise-agentic-ai-config-management-2026',
          ],
        },
        {
          type: 'category',
          label: 'Harness',
          items: [
            'agentic-systems/harness/index',
            'agentic-systems/harness/Harness_Engineering_Research_Report',
            'agentic-systems/harness/Harness_Engineering_AI_Agents_and_Vendor_Landscape',
            'agentic-systems/harness/Harness_BestPractices_AntiPatterns_Roadmap',
            'agentic-systems/harness/Harness_Security_SupplyChain_Observability',
            'agentic-systems/harness/Harness_Interview_Question_Bank',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Agentic UI & Applications',
      items: [
        'agentic-ui/index',
        'agentic-ui/evolution-human-ai-interfaces',
        'agentic-ui/agui-standards-landscape',
        'agentic-ui/enterprise-reference-architecture',
        'agentic-ui/application-lifecycle',
        'agentic-ui/reliability-engineering',
        'agentic-ui/scalability-engineering',
        'agentic-ui/performance-engineering',
        'agentic-ui/security-architecture',
        'agentic-ui/context-engineering',
        'agentic-ui/agent-ux-patterns',
        'agentic-ui/governance',
        'agentic-ui/responsible-ai',
        'agentic-ui/evaluation-framework',
        'agentic-ui/observability',
        'agentic-ui/devsecops',
        'agentic-ui/anti-patterns',
        'agentic-ui/industry-reference-architectures',
        'agentic-ui/decision-frameworks',
        'agentic-ui/future-outlook',
        'agentic-ui/identity-auth-architecture',
      ],
    },
    {
      type: 'category',
      label: 'AI Development',
      items: [
        'ai-development/index',
        {
          type: 'category',
          label: 'AIDLC',
          items: [
            'ai-development/aidlc/index',
            {type: 'doc', id: 'ai-development/aidlc/AIDLC_Enterprise_Framework_2025', label: 'Enterprise Framework (8-Phase Model)'},
            {type: 'doc', id: 'ai-development/aidlc/EA_AIDLC_Deep_Research_2026', label: 'EA Impact & AI Tooling Revolution'},
            {type: 'doc', id: 'ai-development/aidlc/AIDLC_Agile_CICD_AI_Transformation_2026', label: 'Agile & CI/CD Transformation'},
            {type: 'doc', id: 'ai-development/aidlc/Agile_in_the_Age_of_Agentic_AI_2026', label: 'Agile in the Age of Agentic AI'},
            {type: 'doc', id: 'ai-development/aidlc/AIDLC_Artifact_Reference_Library', label: 'Artifact Reference Library'},
          ],
        },
        {
          type: 'category',
          label: 'Testing & Evaluation',
          items: [
            'ai-development/testing/index',
            {type: 'doc', id: 'ai-development/testing/AI_Agent_Evaluation_Framework_Complete', label: 'Complete Evaluation Framework'},
            {type: 'doc', id: 'ai-development/testing/AI_Agent_Evaluation_Framework_Guide', label: 'Evaluation Framework Guide (Original PDF — superseded)'},
            'ai-development/testing/Agent_Testing_Monitoring_Evaluation',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'AI Economics',
      items: [
        'ai-economics/index',
        'ai-economics/ai-tokenomics-guide',
        'ai-economics/ai-value-creators-synthesis',
        'ai-economics/foundation-model-companies-2026',
        'ai-economics/enterprise-ai-commercial-analysis-2026',
        'ai-economics/ai-coding-agents-2026',
        'ai-economics/AI-Value-Creator-Deliverables-Pack',
        'ai-economics/Agentic-AI-Use-Case-Value-Lifecycle',
        'ai-economics/AI_Cost_Implementation_Guide_2026',
      ],
    },
    {
      type: 'category',
      label: 'AI Foundations',
      items: [
        'ai-foundations/index',
        'ai-foundations/AI_Native_Architecture_Evolution_Report',
        'ai-foundations/AI_Assistant_Architecture_Research_Report',
        'ai-foundations/AI_Deep_Future_Outlook_2026_2035',
        'ai-foundations/enterprise-agentic-ai-outlook-2026-2030',
        'ai-foundations/AI_Lab_Research_Report_June2026',
        'ai-foundations/The_Agentic_Loop_Enterprise_AI_Architect_Guide',
        'ai-foundations/transformer_architectures',
        'ai-foundations/transformer_concepts_deep',
        {
          type: 'category',
          label: 'Agentic AI Landing Zone (Complete Platform)',
          items: [
            'ai-foundations/agentic_ai_landing_zone_architecture',
            'ai-foundations/agentic_ai_landing_zone_business_layer',
            'ai-foundations/agentic_ai_landing_zone_eu_ai_act',
            'ai-foundations/agentic_ai_landing_zone_playbooks',
            'ai-foundations/agentic_ai_landing_zone_platform_layer',
            'ai-foundations/agentic_ai_landing_zone_context_engineering',
            'ai-foundations/agentic_ai_landing_zone_evaluation',
            'ai-foundations/agentic_ai_landing_zone_multiagent',
            'ai-foundations/agentic_ai_landing_zone_visual_guide',
            'ai-foundations/agentic_ai_landing_zone_memory_architecture',
            'ai-foundations/agentic_ai_landing_zone_tier3_complete',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'AI Protocols',
      items: [
        {type: 'doc', id: 'ai-protocols/index', label: 'Overview & Decision Guide'},
        {
          type: 'category',
          label: 'MCP — Model Context Protocol',
          items: [
            {type: 'doc', id: 'ai-protocols/mcp/index', label: 'Overview'},
            {type: 'doc', id: 'ai-protocols/mcp/MCP_Deep_Research_2026', label: 'Architecture & Capabilities'},
            {type: 'doc', id: 'ai-protocols/mcp/MCP_Enterprise_Security_Governance_Operations_2026', label: 'Enterprise Security & Governance'},
            {type: 'doc', id: 'ai-protocols/mcp/MCP_Harness_AIDLC', label: 'Testing & Evaluation'},
          ],
        },
        {
          type: 'category',
          label: 'A2A — Agent-to-Agent Protocol',
          items: [
            {type: 'doc', id: 'ai-protocols/a2a/index', label: 'Overview'},
          ],
        },
        {
          type: 'category',
          label: 'Authentication & Identity',
          items: [
            {type: 'doc', id: 'ai-protocols/auth/index', label: 'Overview'},
            {type: 'doc', id: 'ai-protocols/auth/auth-standards-reference', label: 'Standards Reference (OAuth 2.1, OIDC)'},
            {type: 'doc', id: 'ai-protocols/auth/auth_identity_flows', label: 'Auth & Identity Flows'},
            {type: 'doc', id: 'ai-protocols/auth/AgentIdentity_Research_2026_v2', label: 'Agent Identity: Concepts & Research'},
            {type: 'doc', id: 'ai-protocols/auth/agent-identity-entra-vs-awsagentcore', label: 'Entra vs AWS AgentCore'},
            {type: 'doc', id: 'ai-protocols/auth/Part3_Identity_OBO_Sessions', label: 'Identity Propagation & Sessions'},
            {
              type: 'category',
              label: 'Entra 3LO Series',
              items: [
                {type: 'doc', id: 'ai-protocols/auth/entra-3lo-agent-auth-standards-architecture', label: 'Vol 1 — Standards & Architecture'},
                {type: 'doc', id: 'ai-protocols/auth/entra-3lo-agent-auth-implementation', label: 'Vol 2 — Implementation Guide'},
                {type: 'doc', id: 'ai-protocols/auth/entra-3lo-agent-auth-multiagent-compliance', label: 'Vol 3 — Multi-Agent Compliance'},
                {type: 'doc', id: 'ai-protocols/auth/entra-3lo-agent-auth-security-review', label: 'Vol 4 — Security Review'},
              ],
            },
            {type: 'doc', id: 'ai-protocols/auth/tool-authentication-connectors', label: 'Tool Authentication & Connectors'},
            {type: 'doc', id: 'ai-protocols/auth/marketplace-connector-auth-patterns', label: 'Marketplace Connector Patterns'},
            {type: 'doc', id: 'ai-protocols/auth/enterprise-ai-platform-auth-survey', label: 'Platform Auth Survey (10 Platforms)'},
          ],
        },
        {
          type: 'category',
          label: 'Emerging Protocols',
          items: [
            {type: 'doc', id: 'ai-protocols/standards/emerging-protocols-overview', label: 'Overview & Landscape'},
            {type: 'doc', id: 'ai-protocols/standards/emerging-protocols-acp-anp', label: 'ACP & ANP — Federated & Decentralized'},
            {type: 'doc', id: 'ai-protocols/standards/emerging-protocols-beyond-mcp-a2a', label: 'Beyond MCP & A2A — Next-Gen Protocols'},
            {type: 'doc', id: 'ai-protocols/standards/emerging-protocols-agui-utcp', label: 'AG-UI & UTCP — UI Streaming'},
            {type: 'doc', id: 'ai-protocols/standards/emerging-protocols-ucp-ap2-nlip-lmos', label: 'UCP, AP2, NLIP & LMOS — Commerce & Payments'},
            {type: 'doc', id: 'ai-protocols/standards/emerging-protocols-crosscutting', label: 'Cross-Cutting: Security & Governance'},
          ],
        },
        {
          type: 'category',
          label: 'Protocol Standards',
          items: [
            {type: 'doc', id: 'ai-protocols/standards/index', label: 'Overview & Governance'},
            {type: 'doc', id: 'ai-protocols/standards/existing-protocol-evolution-agentic-ai', label: 'Protocol Evolution History'},
            {type: 'doc', id: 'ai-protocols/standards/agent-protocol-metadata-headers', label: 'Metadata, Headers & Negotiation'},
            {type: 'doc', id: 'ai-protocols/standards/AI_Protocols_Standards_Service_Industry_Guide_2026', label: 'Service Industry Adoption Guide'},
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Cloud Platforms',
      items: [
        'cloud-platforms/index',
        'cloud-platforms/enterprise-agent-runtime-internals-2026',
        'cloud-platforms/ai-infrastructure-silicon-landscape-2026',
        {
          type: 'category',
          label: 'AWS AgentCore',
          items: [
            'cloud-platforms/aws/index',
            'cloud-platforms/aws/hyperscaler-deep-dive-aws',
            'cloud-platforms/aws/bedrock-agentcore-code-interpreter-architecture',
            'cloud-platforms/aws/agentcore_strands_deep_research_report',
            'cloud-platforms/aws/AWS_Native_Standards_First_Agentic_Architecture',
            {type: 'doc', id: 'cloud-platforms/aws/AWS_Strands_AgentCore_Builder_Journey_Kit', label: 'Strands Builder Journey Kit (v1)'},
            {type: 'doc', id: 'cloud-platforms/aws/AWS_Strands_AgentCore_Delta_Supplement_v2', label: 'Strands Delta Supplement (v2 — new features)'},
            {type: 'doc', id: 'cloud-platforms/aws/AWS_Strands_AgentCore_AdvancedPatterns_v3', label: 'Strands Advanced Patterns (v3 — expert)'},
            'cloud-platforms/aws/AgentCore_Memory_Architecture_Guide',
            'cloud-platforms/aws/AgentCore_Memory_Gaps_Extensions_2026',
            'cloud-platforms/aws/AgentCore_Memory_Operations_DeepDive',
          ],
        },
        {
          type: 'category',
          label: 'Microsoft Azure',
          items: [
            'cloud-platforms/azure/index',
            'cloud-platforms/azure/hyperscaler-deep-dive-azure',
            'cloud-platforms/azure/azure_agent_architecture',
          ],
        },
        {
          type: 'category',
          label: 'Google Cloud',
          items: [
            'cloud-platforms/gcp/index',
            'cloud-platforms/gcp/hyperscaler-deep-dive-gcp',
          ],
        },
        {
          type: 'category',
          label: 'AI Gateway',
          items: [
            'cloud-platforms/ai-gateway/index',
            'cloud-platforms/ai-gateway/kong-ai-gateway-guide',
            'cloud-platforms/ai-gateway/kong-entra-id-integration',
            'cloud-platforms/ai-gateway/AI_Gateway_Full_Comparison',
            'cloud-platforms/ai-gateway/AI_Gateway_MultiTenant_MultiCloud',
            'cloud-platforms/ai-gateway/Enterprise_AI_Gateway',
          ],
        },
        {
          type: 'category',
          label: 'Kubernetes',
          items: [
            'cloud-platforms/kubernetes/index',
            'cloud-platforms/kubernetes/K8s_Handbook_Part1_Infrastructure_Evolution',
            'cloud-platforms/kubernetes/K8s_Handbook_Part2_Linux_Foundations',
            'cloud-platforms/kubernetes/K8s_Handbook_Part3_Containers',
            'cloud-platforms/kubernetes/K8s_Handbook_Part4_Kubernetes_Internals',
            'cloud-platforms/kubernetes/K8s_Handbook_Part5_Kubernetes_Resources',
            'cloud-platforms/kubernetes/K8s_Handbook_Part6_Kubernetes_Networking',
            'cloud-platforms/kubernetes/K8s_Handbook_Part7_Storage',
            'cloud-platforms/kubernetes/K8s_Handbook_Part8_Security',
            'cloud-platforms/kubernetes/K8s_Handbook_Part9_Platform_Engineering',
            'cloud-platforms/kubernetes/K8s_Handbook_Part10_Observability',
            'cloud-platforms/kubernetes/K8s_Handbook_Part11_AI_Infrastructure',
            'cloud-platforms/kubernetes/K8s_Handbook_Part12_Agentic_AI',
            'cloud-platforms/kubernetes/K8s_Handbook_Part13_Emerging_Standards',
            'cloud-platforms/kubernetes/K8s_Handbook_Part14_Reference_Architectures',
            'cloud-platforms/kubernetes/K8s_Handbook_Part15_Implementation_Labs',
            'cloud-platforms/kubernetes/K8s_Handbook_Part16_Future_Outlook',
          ],
        },
        {
          type: 'category',
          label: 'Infrastructure as Code',
          items: [
            'cloud-platforms/iac/index',
            {
              type: 'category',
              label: 'Terraform',
              items: [
                'cloud-platforms/iac/terraform/index',
                'cloud-platforms/iac/terraform/terraform-mastery-guide',
                'cloud-platforms/iac/terraform/ai-assisted-iac-mastery',
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Coding Tools',
      items: [
        'coding-tools/index',
        {
          type: 'category',
          label: 'Claude',
          items: [
            'coding-tools/claude/index',
            'coding-tools/claude/claude-models-2026',
            'coding-tools/claude/claude-api-mastery',
            'coding-tools/claude/claude-code-complete-2026',
            'coding-tools/claude/claude-agent-sdk-production',
            'coding-tools/claude/prompt-engineering-claude-4',
            'coding-tools/claude/claude-enterprise-2026',
            'coding-tools/claude/constitutional-ai-safety-2026',
            'coding-tools/claude/mcp-deep-guide',
            'coding-tools/claude/ccaf-exam-prep-complete',
            'coding-tools/claude/ruflo-agentic-ai-guide',
            'coding-tools/claude/claude-best-practices',
            'coding-tools/claude/claude_agents_best_practices_v2',
            'coding-tools/claude/Claude_Ecosystem_Research_Report',
            'coding-tools/claude/Anthropic_Partner_Cert_Study_Guide',
            'coding-tools/claude/CCAF_Study_Guide',
            'coding-tools/claude/CCAF_Advanced_Supplement',
            'coding-tools/claude/Module_1_Claude_Foundations',
            'coding-tools/claude/Module_3_Prompt_Engineering',
            'coding-tools/claude/Module_4_MCP',
            'coding-tools/claude/Module_5_Claude_Code_Agents',
            'coding-tools/claude/Module_6_Claude_Workflows',
            'coding-tools/claude/Module_7_Safety_Enterprise_Exam',
            {
              type: 'category',
              label: 'Cheatsheets & Quick Reference',
              items: [
                'coding-tools/claude/Cheatsheet_1_Claude_Code',
                'coding-tools/claude/Cheatsheet_2_Agent_SDK',
                'coding-tools/claude/Cheatsheet_3_MCP',
                'coding-tools/claude/Cheatsheet_4_AI_Fluency',
                'coding-tools/claude/Cheatsheet_5_Prompt_Engineering',
                'coding-tools/claude/Cheatsheet_6_Claude_CLI',
                'coding-tools/claude/Cheatsheet_7_Claude_Ecosystem',
                'coding-tools/claude/Cheatsheet_9_Agents_Parallelism',
                'coding-tools/claude/Cheatsheet_10_MultiAgent_Production',
                'coding-tools/claude/Cheatsheet_11_MCP_Pipeline_Errors',
                'coding-tools/claude/claude_routines_guide',
                'coding-tools/claude/Questionnaire_Claude_Certification',
                'coding-tools/claude/Questionnaire_Vol2_Claude_Certification',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'GitHub Copilot',
          items: [
            'coding-tools/github-copilot/index',
            'coding-tools/github-copilot/github-copilot-zero-to-hero',
            'coding-tools/github-copilot/git-github-platform-engineering-handbook',
            'coding-tools/github-copilot/copilot-enterprise-playbook',
            'coding-tools/github-copilot/github-copilot-big-wins-research',
            'coding-tools/github-copilot/GitHub_Copilot_Enterprise_Research_2026',
            'coding-tools/github-copilot/Part01_Git_Internals',
            'coding-tools/github-copilot/Part01_Vision_Copilot_Architecture_RepoIntelligence',
            'coding-tools/github-copilot/Part02_GitHub_Architecture_and_Actions',
            'coding-tools/github-copilot/Part04_RAG_Agents_Models_Platform',
            'coding-tools/github-copilot/Part04_Runners_and_Runtime',
            'coding-tools/github-copilot/Part06_Marketplace_Pages_Packages',
            'coding-tools/github-copilot/Part07_Prompts_Evaluation_Spark_Infrastructure',
            'coding-tools/github-copilot/Part11_CICD_Secrets_Security',
            'coding-tools/github-copilot/Part11_Security_Governance',
            'coding-tools/github-copilot/Part13_CICD_Observability_Scaling',
            'coding-tools/github-copilot/Part14_Enterprise_APIs_Apps_CLI',
            'coding-tools/github-copilot/Part16_Artifacts_ReferenceArchitecture',
            'coding-tools/github-copilot/Part18_Ecosystem_Patterns_Labs',
            'coding-tools/github-copilot/copilotkit-mcp-apps-vs-tools',
            'coding-tools/github-copilot/copilotkit-server-map-call-flow',
            'coding-tools/github-copilot/microsoft-apm-guide',
          ],
        },
        {
          type: 'category',
          label: 'Code Review',
          items: [
            'coding-tools/code-review/index',
            'coding-tools/code-review/PR_Review_Handbook_Vol1_Traditional_Review',
            'coding-tools/code-review/PR_Review_Handbook_Vol2_Deep_Domain_Reviews',
            'coding-tools/code-review/PR_Review_Handbook_Vol3_AI_Assisted_Review',
            'coding-tools/code-review/PR_Review_Handbook_Vol4_Agentic_Review_Architecture',
            'coding-tools/code-review/PR_Review_Handbook_Vol5_Case_Studies_Maturity_Model',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Cyber Security Architecture',
      items: [
        'cybersec-architect/index',
        'cybersec-architect/01-evolution',
        'cybersec-architect/02-enterprise-security-architecture',
        'cybersec-architect/03-security-domains',
        'cybersec-architect/04-ai-security',
        'cybersec-architect/05-agentic-ai-security',
        'cybersec-architect/06-identity-architecture',
        'cybersec-architect/07-cloud-security',
        'cybersec-architect/08-ai-governance',
        'cybersec-architect/09-security-operations',
        'cybersec-architect/10-technology-investment',
        'cybersec-architect/11-ai-investment',
        'cybersec-architect/12-ea-deliverables',
        'cybersec-architect/13-security-patterns',
        'cybersec-architect/14-case-studies',
        'cybersec-architect/15-emerging-trends',
        'cybersec-architect/usecase-transcript',
      ],
    },
    {
      type: 'category',
      label: 'EA Masterclass',
      items: [
        'ea-masterclass/index',
        'ea-masterclass/module-01-ea-foundations/index',
        'ea-masterclass/module-02-business-acumen/index',
        'ea-masterclass/module-03-proposal-lifecycle/index',
        'ea-masterclass/module-04-technology-investment/index',
        'ea-masterclass/module-05-ai-investment-strategy/index',
        'ea-masterclass/module-06-business-case/index',
        'ea-masterclass/module-07-proposal-writing/index',
        'ea-masterclass/module-08-financial-literacy/index',
        'ea-masterclass/module-09-enterprise-ai-architecture/index',
        'ea-masterclass/module-10-governance/index',
        'ea-masterclass/module-11-executive-communication/index',
        'ea-masterclass/module-12-ai-consulting/index',
        {
          type: 'category',
          label: 'Module 13: Case Studies',
          items: [
            'ea-masterclass/module-13-case-studies/index',
            'ea-masterclass/module-13-case-studies/global-bank',
            'ea-masterclass/module-13-case-studies/healthcare',
            'ea-masterclass/module-13-case-studies/manufacturing',
            'ea-masterclass/module-13-case-studies/retail',
            'ea-masterclass/module-13-case-studies/telecom',
            'ea-masterclass/module-13-case-studies/government',
            'ea-masterclass/module-13-case-studies/energy-utilities',
          ],
        },
        {
          type: 'category',
          label: 'Module 14: Mentoring & Mastery',
          items: [
            'ea-masterclass/module-14-mentoring/index',
          ],
        },
        {
          type: 'category',
          label: 'Module 15: Distinguished Architect',
          items: [
            'ea-masterclass/module-15-distinguished-architect/index',
            'ea-masterclass/module-15-distinguished-architect/executive-presence',
            'ea-masterclass/module-15-distinguished-architect/strategic-thinking',
            'ea-masterclass/module-15-distinguished-architect/architecture-leadership',
            'ea-masterclass/module-15-distinguished-architect/fortune100-modernisation',
          ],
        },
        {
          type: 'category',
          label: 'Templates & Deliverables',
          items: [
            'ea-masterclass/deliverables/index',
            'ea-masterclass/deliverables/business-case-templates',
            'ea-masterclass/deliverables/governance-templates',
            'ea-masterclass/deliverables/consulting-templates',
          ],
        },
        {
          type: 'category',
          label: 'Workshop Transcripts',
          items: [
            'ea-masterclass/transcripts/index',
            'ea-masterclass/transcripts/bank-discovery-workshop',
            'ea-masterclass/transcripts/healthcare-executive-presentation',
            'ea-masterclass/transcripts/manufacturing-arb-review',
            'ea-masterclass/transcripts/retail-proposal-negotiation',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Enterprise Architecture',
      items: [
        'enterprise-architecture/index',
        {
          type: 'category',
          label: 'Strategy',
          items: [
            'enterprise-architecture/strategy/index',
            'enterprise-architecture/strategy/EA_Strategy_Playbook',
            'enterprise-architecture/strategy/Enterprise_AI_Strategic_Brief_2026',
            'enterprise-architecture/strategy/Enterprise_AI_Transformation_Blueprint_CTO_Guide_2026',
            'enterprise-architecture/strategy/EA_AI_First_Transformation_Transcript',
          ],
        },
        {
          type: 'category',
          label: 'Frameworks',
          items: [
            'enterprise-architecture/framework/index',
            'enterprise-architecture/framework/TOGAF10_APEX_AI_Platform_NexaBank',
            'enterprise-architecture/framework/Enterprise_AI_Architect_Communication_Guide',
            'enterprise-architecture/framework/Executive_Communication_Framework_Guide',
            'enterprise-architecture/framework/EA_Soft_Skills_Interview_Master_Guide',
          ],
        },
        {
          type: 'category',
          label: 'Processes',
          items: [
            'enterprise-architecture/process/index',
            'enterprise-architecture/process/enterprise-technology-selection-framework',
            'enterprise-architecture/process/ai-solution-lifecycle-deliverables',
            'enterprise-architecture/process/Enterprise_AI_Architect_Bible_2026',
            'enterprise-architecture/process/Enterprise_AI_Architect_Deep_Dive_Guide',
            'enterprise-architecture/process/Enterprise_Agentic_AI_Architecture_Playbook_2026',
            'enterprise-architecture/process/EA_Lifecycle_Artifact_Templates_2026',
            'enterprise-architecture/process/EA_Lifecycle_Checklist',
            'enterprise-architecture/process/EA_Mastery_Guide',
            'enterprise-architecture/process/EA_Real_Life_Transcript',
          ],
        },
        {
          type: 'category',
          label: 'Best Practices',
          items: [
            'enterprise-architecture/best-practices/index',
            'enterprise-architecture/best-practices/EA_BestPractices_Jargon',
            'enterprise-architecture/best-practices/EA_Glossary_CheatSheet',
          ],
        },
        {
          type: 'category',
          label: 'ARB',
          items: [
            'enterprise-architecture/architectural-review-board/index',
            'enterprise-architecture/architectural-review-board/Volume1_Governance_Ecosystem_Operating_Models',
            'enterprise-architecture/architectural-review-board/Volume2_Economics_Decision_Science',
            'enterprise-architecture/architectural-review-board/Volume3_Knowledge_Management_Capability_Mapping',
            'enterprise-architecture/architectural-review-board/Volume4_Artifact_Catalog_Quality_Attributes',
            'enterprise-architecture/architectural-review-board/Volume5_Review_Questions_Scorecards',
            'enterprise-architecture/architectural-review-board/Volume6_Banking_Industry_DeepDive',
            'enterprise-architecture/architectural-review-board/Volume7_AI_Native_ARB_Case_Studies',
            'enterprise-architecture/architectural-review-board/Volume8_Implementation_Accelerator_Kit',
            'enterprise-architecture/architectural-review-board/Volume9_Enterprise_Reference_Repository',
            'enterprise-architecture/architectural-review-board/Volume10_Collaborative_Use_Case_Transcripts',
          ],
        },
        {
          type: 'category',
          label: 'Specialization',
          items: [
            'enterprise-architecture/specialization/index',
            'enterprise-architecture/specialization/APEX_EA_Final',
            'enterprise-architecture/specialization/DSA_Principal_Architect_Reference',
            'enterprise-architecture/specialization/Principal_Enterprise_AI_Guide_Educative',
            'enterprise-architecture/specialization/AI_Transformation_Consultant_Toolkit_2026',
            'enterprise-architecture/specialization/Enterprise_Data_Architect_AI_GenAI',
            'enterprise-architecture/specialization/Enterprise_Manager_AI_GenAI',
            'enterprise-architecture/specialization/EA_OKR_KPI_Research',
            'enterprise-architecture/specialization/EA_Business_Communication_Executive_Skills',
            'enterprise-architecture/specialization/AI_Invoice_Auditor_Architecture_v5',
            'enterprise-architecture/specialization/RFI_AI_Platform_Transcript',
            'enterprise-architecture/specialization/AKES_Addendum_Document_Update_and_Versioning',
            'enterprise-architecture/specialization/DPDP_Act_2023_Comprehensive_Guide',
            'enterprise-architecture/specialization/EAKA_Research_Study',
            'enterprise-architecture/specialization/modern-data-ai-platform-blueprint-2026',
          ],
        },
        {
          type: 'category',
          label: 'AI Architecture',
          items: [
            'enterprise-architecture/ai-architecture/index',
            'enterprise-architecture/ai-architecture/ART-Framework-Agentic-AI-Execution',
            'enterprise-architecture/ai-architecture/AgentOps-Production-Guide',
            {
              type: 'category',
              label: 'AI FinOps',
              items: [
                'enterprise-architecture/ai-architecture/AI-FinOps-Cost-Management-Guide',
                'enterprise-architecture/ai-architecture/ai-finops-multi-agent-cost-propagation',
                'enterprise-architecture/ai-architecture/ai-finops-chargeback-attribution',
                'enterprise-architecture/ai-architecture/ai-finops-budget-governance',
                'enterprise-architecture/ai-architecture/ai-finops-unit-economics-kpis',
                'enterprise-architecture/ai-architecture/ai-finops-rag-mcp-a2a-economics',
                'enterprise-architecture/ai-architecture/ai-finops-capacity-forecasting',
                'enterprise-architecture/ai-architecture/ai-finops-infrastructure-optimization',
                'enterprise-architecture/ai-architecture/ai-finops-maturity-model',
              ],
            },
            'enterprise-architecture/ai-architecture/AI-Value-Stream-Mapping',
            'enterprise-architecture/ai-architecture/enterprise-ai-architect-foundations',
            'enterprise-architecture/ai-architecture/enterprise-multi-model-ai-strategy',
            'enterprise-architecture/ai-architecture/enterprise-ai-comparative-matrices-2026',
            'enterprise-architecture/ai-architecture/enterprise-ai-architecture-patterns',
            'enterprise-architecture/ai-architecture/enterprise-ai-governance-compliance',
            'enterprise-architecture/ai-architecture/enterprise-ai-skills-assessment',
            'enterprise-architecture/ai-architecture/agentic-ai-security-identity',
            'enterprise-architecture/ai-architecture/agent-interoperability-orchestration',
            'enterprise-architecture/ai-architecture/machine-readable-ea',
            'enterprise-architecture/ai-architecture/agentic-ai-security-guardrails',
            'enterprise-architecture/ai-architecture/agentic-ai-reliability-observability-governance',
            'enterprise-architecture/ai-architecture/agent-reliability-engineering',
            'enterprise-architecture/ai-architecture/enterprise-aiops-guide',
            'enterprise-architecture/ai-architecture/ai-harness-architecture-orchestration',
            'enterprise-architecture/ai-architecture/a2a-enterprise-security-governance-guide',
            'enterprise-architecture/ai-architecture/mcp-a2a-protocol-deep-dive',
            'enterprise-architecture/ai-architecture/agent-memory-planning-architecture',
            'enterprise-architecture/ai-architecture/agent-communication-identity-gateway',
            'enterprise-architecture/ai-architecture/enterprise-agent-reference-architectures',
            {
              type: 'category',
              label: 'Advanced Multi-Agent Architecture',
              items: [
                'enterprise-architecture/ai-architecture/multi-agent-topology-patterns',
                'enterprise-architecture/ai-architecture/agent-as-tool-composition',
                'enterprise-architecture/ai-architecture/governance-propagation-chain',
                'enterprise-architecture/ai-architecture/end-to-end-traceability-guide',
                'enterprise-architecture/ai-architecture/drift-detection-guide',
                'enterprise-architecture/ai-architecture/kill-switch-architecture',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Transformation',
          items: [
            'enterprise-architecture/transformation/index',
            'enterprise-architecture/transformation/ai-first-to-ai-native',
            'enterprise-architecture/transformation/00_Executive_Summary_and_AI_Vision',
            'enterprise-architecture/transformation/01_Current_State_Assessment_and_AI_Maturity',
            'enterprise-architecture/transformation/02_AI_Opportunity_Portfolio',
            'enterprise-architecture/transformation/03_Enterprise_AI_Platform_and_Data_Architecture',
            'enterprise-architecture/transformation/04_Governance_Responsible_AI_and_Security',
            'enterprise-architecture/transformation/05_Target_Operating_Model_and_Change',
            'enterprise-architecture/transformation/06_Roadmap_Financials_KPIs_and_Risk',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Interview Prep',
      items: [
        'interview-prep/index',
        {
          type: 'category',
          label: 'EA Interviews',
          items: [
            'interview-prep/ea/index',
            {type: 'doc', id: 'interview-prep/ea/EA_Interview_Handbook', label: 'EA Interview Handbook (Vol 1)'},
            {type: 'doc', id: 'interview-prep/ea/EA_Interview_Handbook_DELTA', label: 'EA Interview Handbook — Delta (Vol 2: 12 new topics)'},
            'interview-prep/ea/EA_Interview_Master_Guide',
            'interview-prep/ea/EA_Interview_Vol3_CTO_AI',
          ],
        },
        {
          type: 'category',
          label: 'Forward Deployed Engineer (FDE)',
          items: [
            'interview-prep/fde/index',
            'interview-prep/fde/fde-role-skills-map',
            'interview-prep/fde/fde-life-transcript',
            'interview-prep/fde/architect-in-fde-context',
          ],
        },
        'interview-prep/Enterprise_Architect_in_the_Age_of_AI',
        'interview-prep/ea-ai-artifacts-and-metrics',
        'interview-prep/EA_Soft_Skills_and_Behaviors',
        'interview-prep/EA_Senior_Interview_Questions',
        'interview-prep/EA_Quality_Resilience_Testing_Interview_Questions',
        'interview-prep/EA_HITL_HOTL_HOOL_Interview_Questions',
        'interview-prep/AI_Agent_Systems_Interview_Guide',
        'interview-prep/AI_Engineer_Question_Bank',
        'interview-prep/Agentic_AI_Platforms_Questionnaire_2025',
        'interview-prep/EY_AI_Architect_Interview_Guide_1',
        'interview-prep/Enterprise_GenAI_Architect_Interview_Guide',
        'interview-prep/Hard_Scenarios_Interview_Prep',
        {type: 'doc', id: 'interview-prep/Multimodal_AI_EA_Scenarios', label: 'Multimodal AI — EA Complex Scenarios'},
        'interview-prep/ML_AI_Interview_Mastery_Guide',
      ],
    },
    {
      type: 'category',
      label: 'Knowledge',
      items: [
        'knowledge-engineering/index',
        {
          type: 'category',
          label: 'Data Architecture',
          items: [
            'knowledge-engineering/data/index',
            'knowledge-engineering/data/Data_Architecture_for_AI_Report',
            'knowledge-engineering/data/End_to_End_Lineage_Systems_Report',
            'knowledge-engineering/data/Enterprise_Data_Systems_AI_Governance_Report',
          ],
        },
        {
          type: 'category',
          label: 'Knowledge & RAG',
          items: [
            'knowledge-engineering/knowledge/index',
            'knowledge-engineering/knowledge/Enterprise_Knowledge_Architectures_Report',
            'knowledge-engineering/knowledge/Complex_RAG_Deep_Dive',
            'knowledge-engineering/knowledge/Autonomous_Knowledge_Engineering_System',
          ],
        },
        {
          type: 'category',
          label: 'Industry Knowledge Systems',
          items: [
            'knowledge-engineering/industry-practices/index',
            'knowledge-engineering/industry-practices/tech-companies',
            'knowledge-engineering/industry-practices/consulting-firms-genai-strategy',
            'knowledge-engineering/industry-practices/consulting-firms',
            'knowledge-engineering/industry-practices/governance-rai',
            'knowledge-engineering/industry-practices/grounding',
            'knowledge-engineering/industry-practices/evaluation',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Quantum AI',
      link: {type: 'doc', id: 'quantum/index'},
      items: [
        {type: 'doc', id: 'quantum/zero-to-mastery', label: 'Zero to Mastery'},
        {type: 'doc', id: 'quantum/Quantum_AI_Zero_to_Mastery', label: 'Quantum AI Zero to Mastery (Original PDF — superseded)'},
        {type: 'doc', id: 'quantum/IBM_Associate_Quantum_CertGuide', label: 'IBM Associate Cert Guide'},
        {type: 'doc', id: 'quantum/IBM_Developer_Quantum_CertGuide', label: 'IBM Developer Cert Guide'},
        {type: 'doc', id: 'quantum/Quantum_AI_TechGiants_Report', label: 'Tech Giants Report'},
        {type: 'doc', id: 'quantum/Quantum_AI_Startups_Report', label: 'Startups Report'},
        {type: 'doc', id: 'quantum/Quantum_AI_Consultancies_Report', label: 'Consultancies Report'},
      ],
    },
    {
      type: 'category',
      label: 'Security',
      items: [
        'ai-security-governance/index',
        {
          type: 'category',
          label: 'AI Security',
          items: [
            'ai-security-governance/security/index',
            'ai-security-governance/security/AI-TRiSM-Complete-Guide',
            'ai-security-governance/security/AIDR-AI-Detection-Response-Complete-Guide',
            'ai-security-governance/security/AISPM-AI-Security-Posture-Management',
            'ai-security-governance/security/AI-Red-Teaming-Guide',
            'ai-security-governance/security/AI-Bill-of-Materials-Guide',
            'ai-security-governance/security/Model-Cards-System-Cards-Guide',
            'ai-security-governance/security/01-Foundations-Reference-Architecture',
            'ai-security-governance/security/02-Identity-MCP-A2A-Security-Blueprint',
            'ai-security-governance/security/Part4_Runtime_Security_Governance',
            'ai-security-governance/security/04-AI-SOC-Observability-RedTeam-Memory',
            'ai-security-governance/security/05-Economic-Security-FinOps-Commerce-PQC',
            'ai-security-governance/security/06-Operating-Model-Maturity-Roadmap',
            'ai-security-governance/security/07-Zero-to-Mastery-Curriculum',
            'ai-security-governance/security/08-Architects-Field-Guide',
            'ai-security-governance/security/Part1_Industry_Survey',
            'ai-security-governance/security/Part5_Marketplace_Architecture',
            'ai-security-governance/security/Part7_Standards_Reference',
            'ai-security-governance/security/08-Future-AI-SOC-2026-2030',
          ],
        },
        'ai-security-governance/Agentic_AI_Governance_Framework',
        'ai-security-governance/Sovereign_Constitutional_AI_RAI_Implementation_Handbook',
        {
          type: 'category',
          label: 'DeepMind AI Control Series',
          items: [
            'ai-security-governance/deep-mind/index',
            'ai-security-governance/deep-mind/Part01_DeepMind_AI_Control_Roadmap',
            'ai-security-governance/deep-mind/Part02_Evolution_Enterprise_AI_Security',
            'ai-security-governance/deep-mind/Part03_Enterprise_Threat_Modeling',
            'ai-security-governance/deep-mind/Part04_AI_Control_Architecture',
            'ai-security-governance/deep-mind/Part05_Runtime_AI_Security',
            'ai-security-governance/deep-mind/Part06_Identity_for_AI_Agents',
            'ai-security-governance/deep-mind/Part07_AI_Authorization',
            'ai-security-governance/deep-mind/Part08_Memory_Governance',
            'ai-security-governance/deep-mind/Part09_Tool_Governance',
            'ai-security-governance/deep-mind/Part10_Reasoning_Governance',
            'ai-security-governance/deep-mind/Part11_Multi_Agent_Security',
            'ai-security-governance/deep-mind/Part12_AI_Observability',
            'ai-security-governance/deep-mind/Part13_AI_SOC',
            'ai-security-governance/deep-mind/Part14_Enterprise_Governance',
            'ai-security-governance/deep-mind/Part15_Cloud_Implementation_Comparison',
            'ai-security-governance/deep-mind/Part16_Reference_Architecture',
            'ai-security-governance/deep-mind/Part17_Best_Practices_Anti_Patterns',
            'ai-security-governance/deep-mind/Part18_Future_Outlook_2026_2035',
          ],
        },
        {
          type: 'category',
          label: 'Policy & Authorization Series',
          items: [
            'ai-security-governance/policy/index',
            'ai-security-governance/policy/Vol0_Series_Index_and_Overview',
            'ai-security-governance/policy/Vol1_Executive_Architecture',
            'ai-security-governance/policy/Vol1b_Authorization_Deep_Dive',
            'ai-security-governance/policy/Vol2_Identity_Claims_Policy',
            'ai-security-governance/policy/Vol2b_Advanced_Policy_Engineering',
            'ai-security-governance/policy/Vol3_Agent_Tool_MCP_Authorization',
            'ai-security-governance/policy/Vol3b_Agent_Authorization_Deep_Dive',
            'ai-security-governance/policy/Vol4_RAG_Memory_Data_Authorization',
            'ai-security-governance/policy/Vol4b_AWS_Entra_Federation_Patterns',
            'ai-security-governance/policy/Vol5_AWS_Implementation_Governance',
            'ai-security-governance/policy/Vol5b_Compliance_Governance_Decision_Framework',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Soft Skills',
      items: [
        'soft-skills/index',
        'soft-skills/Problem_Solving_Skills',
        'soft-skills/Creative_Thinking_Skills',
        'soft-skills/CTO_Voice_Mastery_Program',
        'soft-skills/Mental_Models_for_Voice_Training',
        'soft-skills/Storytelling_Exercise_Workbook',
        'soft-skills/Voice_Training_30Day_Plan',
        'soft-skills/Mental_Model_Encyclopedia',
        'soft-skills/Strategic_Thinking_Handbook',
      ],
    },
    {
      type: 'category',
      label: 'Sovereign & Constitutional AI',
      items: [
        'sovereign-constitutional-ai/index',
        'sovereign-constitutional-ai/sovereign-ai-foundations',
        'sovereign-constitutional-ai/constitutional-ai-engineering',
        'sovereign-constitutional-ai/rai-operating-model',
        'sovereign-constitutional-ai/ai-alignment-control',
        'sovereign-constitutional-ai/ai-governance-operating-model',
        'sovereign-constitutional-ai/ai-risk-taxonomy',
        'sovereign-constitutional-ai/ai-safety-framework',
        'sovereign-constitutional-ai/ai-assurance-audit-architecture',
        'sovereign-constitutional-ai/constitutional-agent-architecture',
        'sovereign-constitutional-ai/policy-as-code-framework',
        'sovereign-constitutional-ai/democratic-ai-public-interest',
        'sovereign-constitutional-ai/sovereign-ai-roadmap-maturity',
      ],
    },
    {
      type: 'category',
      label: 'Use Cases',
      items: [
        'ai-usecases/index',
        'ai-usecases/EU_Banking_AI_Evaluation_Compliance_Guide',
        'ai-usecases/EU_Banking_AI_Agent_Evaluation_Framework',
        {
          type: 'category',
          label: 'EU Bank AI Copilot',
          items: [
            'ai-usecases/eu-bank-ai-copilot-complete',
            'ai-usecases/eu-bank-ai-copilot-architecture',
            'ai-usecases/eu-bank-sequence-diagrams',
          ],
        },
        'ai-usecases/airgapped-banking-architecture',
        'ai-usecases/CEO_Agent_Solution_Blueprint',
        'ai-usecases/CEO_Agent_Failure_Modes_Governance_Harness',
        'ai-usecases/ceo_agent_pitch',
        'ai-usecases/Enterprise_AI_Case_Studies',
        'ai-usecases/Part6_Banking_Case_Study',
        {
          type: 'category',
          label: 'Industry Verticals',
          items: [
            'ai-usecases/01_aviation',
            'ai-usecases/02_banking',
            'ai-usecases/03_healthcare',
            'ai-usecases/04_manufacturing',
            'ai-usecases/05_telecom',
            'ai-usecases/06_government',
            'ai-usecases/07_pharma',
            'ai-usecases/08_energy',
            'ai-usecases/09_logistics',
            'ai-usecases/10_media',
          ],
        },
        {
          type: 'category',
          label: 'Agentic Case Studies',
          items: [
            'ai-usecases/Case_01_Meridian_Fraud_Investigation_Agents',
            'ai-usecases/Case_02_Cascadia_Prior_Authorization_Agent',
            'ai-usecases/Case_03_Ironclad_Maintenance_Orchestration_Agent',
            'ai-usecases/Case_04_Northline_Customer_Service_Agents',
            'ai-usecases/Case_05_Aurelia_Research_Assistant_Agent',
            'ai-usecases/Case_06_Skyline_Disruption_Control_Tower',
            'ai-usecases/Case_07_Harborstone_Claims_Processing_Agents',
            'ai-usecases/Case_08_Sterling_Loan_Underwriting_Agent',
            'ai-usecases/Case_09_Palisade_Grid_Operations_Agent',
            'ai-usecases/Case_10_Vantara_Procurement_Negotiation_Agents',
            'ai-usecases/Case_11_Vaxion_Clinical_Trial_Matching_Agent',
            'ai-usecases/Case_12_Meritage_Dynamic_Pricing_Agent',
            'ai-usecases/Case_13_StateDHS_Benefits_Navigation_Agent',
            'ai-usecases/Case_14_Falkirk_SOC_Threat_Response_Agent',
            'ai-usecases/Case_15_Correlate_Recruiting_Screening_Agent',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Workflow Orchestration',
      items: [
        'workflow-orchestration/index',
        'workflow-orchestration/01-executive-summary',
        'workflow-orchestration/02-evolution-timeline',
        'workflow-orchestration/03-workflow-vs-agent-architecture',
        'workflow-orchestration/06-durable-vs-cognitive-execution',
        'workflow-orchestration/04-temporal-deep-dive',
        'workflow-orchestration/05-camunda-deep-dive',
        'workflow-orchestration/07-ai-coding-orchestrators',
        'workflow-orchestration/08-agent-frameworks-comparison',
        'workflow-orchestration/09-tool-calling-orchestration',
        'workflow-orchestration/10-mcp-impact',
        'workflow-orchestration/11-a2a-orchestration-patterns',
        'workflow-orchestration/14-ai-planning-vs-workflow-engines',
        'workflow-orchestration/12-human-in-the-loop-architectures',
        'workflow-orchestration/13-memory-vs-workflow-state',
        'workflow-orchestration/15-reliability-playbook',
        'workflow-orchestration/16-observability-framework',
        'workflow-orchestration/17-security-architecture',
        'workflow-orchestration/18-enterprise-governance-model',
        'workflow-orchestration/19-reference-architectures',
        'workflow-orchestration/20-decision-matrix',
        'workflow-orchestration/22-anti-patterns-catalog',
        'workflow-orchestration/23-capability-maturity-model',
        'workflow-orchestration/21-future-predictions',
      ],
    },
    {
      type: 'category',
      label: 'AI SOC Automation Playbooks',
      items: [
        'ai-soc-playbooks/index',
        {type: 'doc', id: 'ai-soc-playbooks/part-01-soc-operating-model', label: 'Part 01 — SOC Operating Model'},
        {type: 'doc', id: 'ai-soc-playbooks/part-02-ai-use-cases', label: 'Part 02 — AI Use Cases'},
        {type: 'doc', id: 'ai-soc-playbooks/part-03-agentic-soc', label: 'Part 03 — Agentic SOC Architecture'},
        {type: 'doc', id: 'ai-soc-playbooks/part-04-automation-playbooks', label: 'Part 04 — 17 Automation Playbooks'},
        {type: 'doc', id: 'ai-soc-playbooks/part-05-soar-platforms', label: 'Part 05 — SOAR Platforms'},
        {type: 'doc', id: 'ai-soc-playbooks/part-06-ai-models', label: 'Part 06 — AI Models & Prompting'},
        {type: 'doc', id: 'ai-soc-playbooks/part-07-ai-safety', label: 'Part 07 — AI Safety & Guardrails'},
        {type: 'doc', id: 'ai-soc-playbooks/part-08-observability', label: 'Part 08 — Observability & Evaluation'},
        {type: 'doc', id: 'ai-soc-playbooks/part-09-enterprise-architecture', label: 'Part 09 — Enterprise Architecture'},
        {type: 'doc', id: 'ai-soc-playbooks/part-10-standards-compliance', label: 'Part 10 — Standards & Compliance'},
        {type: 'doc', id: 'ai-soc-playbooks/part-11-implementation-roadmap', label: 'Part 11 — Implementation Roadmap'},
        {type: 'doc', id: 'ai-soc-playbooks/part-12-finops', label: 'Part 12 — FinOps & Cost Management'},
        {type: 'doc', id: 'ai-soc-playbooks/part-13-vendor-landscape', label: 'Part 13 — Vendor Landscape'},
        {type: 'doc', id: 'ai-soc-playbooks/part-14-future-soc', label: 'Part 14 — Future SOC 2030'},
      ],
    },
    {
      type: 'category',
      label: 'NIST AI Standards & CAISI',
      items: [
        'nist-ai-standards/index',
        {type: 'doc', id: 'nist-ai-standards/part-01-nist-ai-100-2-adversarial-ml', label: 'Part 01 — NIST AI 100-2: Adversarial ML'},
        {type: 'doc', id: 'nist-ai-standards/part-02-nist-ai-100-4-synthetic-content', label: 'Part 02 — NIST AI 100-4: Synthetic Content'},
        {type: 'doc', id: 'nist-ai-standards/part-03-caisi-agentic-ai', label: 'Part 03 — CAISI: Agentic AI Security'},
        {type: 'doc', id: 'nist-ai-standards/part-04-enterprise-architecture', label: 'Part 04 — Enterprise Architecture (AWS/Azure/GCP)'},
        {type: 'doc', id: 'nist-ai-standards/part-05-control-mappings', label: 'Part 05 — Cross-Framework Control Mappings'},
        {type: 'doc', id: 'nist-ai-standards/part-06-implementation-checklist', label: 'Part 06 — Implementation Checklist'},
        {type: 'doc', id: 'nist-ai-standards/part-07-future-trends', label: 'Part 07 — Future Trends & Standards Evolution'},
      ],
    },
    {type: 'doc', id: 'about', label: 'About'},
  ], true),
};

module.exports = sidebars;
