// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {type: 'doc', id: 'index', label: 'Home'},
    {
      type: 'category',
      label: 'Agentic AI',
      items: [
        'agentic-systems/index',
        {
          type: 'category',
          label: 'Platform',
          items: [
            'agentic-systems/platform/index',
            'agentic-systems/platform/MultiTenantAgentPlatform_Architecture',
            'agentic-systems/platform/agentic_platform_bestpractices',
            'agentic-systems/platform/ai-platform-factory-runbook-v2',
            'agentic-systems/platform/ai-msf-requirements-runbook',
            'agentic-systems/platform/enterprise-agentic-ai-asset-management-2026',
            'agentic-systems/platform/genaiaf-prompt-lifecycle-hotswap-research-2026',
            'agentic-systems/platform/Enterprise_PromptOps_AWS_AgentCore_2026',
          ],
        },
        {
          type: 'category',
          label: 'Memory',
          items: [
            'agentic-systems/memory/index',
            'agentic-systems/memory/AI_Memory_Agent_Innovations_Research_Report',
          ],
        },
        {
          type: 'category',
          label: 'Agent Skills',
          items: [
            'agentic-systems/skill/index',
            'agentic-systems/skill/executive-summary-and-reference-architecture',
            {
              type: 'category',
              label: 'Enterprise Platform Research',
              items: [
                'agentic-systems/skill/enterprise/index',
                'agentic-systems/skill/enterprise/foundations-what-is-an-agent-skill',
                'agentic-systems/skill/enterprise/skill-anatomy-and-metadata-schema',
                'agentic-systems/skill/enterprise/execution-lifecycle-and-tracing',
                'agentic-systems/skill/enterprise/skills-tools-mcp-a2a-relationship',
                'agentic-systems/skill/enterprise/tool-definition-best-practices',
                'agentic-systems/skill/enterprise/registry-discovery-and-deduplication',
                'agentic-systems/skill/enterprise/composition-and-instructions-engineering',
                'agentic-systems/skill/enterprise/observability-and-evaluation',
                'agentic-systems/skill/enterprise/security-architecture',
                'agentic-systems/skill/enterprise/governance-and-lifecycle',
                'agentic-systems/skill/enterprise/architecture-patterns-antipatterns-and-case-studies',
              ],
            },
            {
              type: 'category',
              label: 'Coding Assistant Research',
              items: [
                'agentic-systems/skill/coding/index',
                'agentic-systems/skill/coding/foundations-what-is-a-coding-skill',
                'agentic-systems/skill/coding/skill-anatomy-and-metadata-schema',
                'agentic-systems/skill/coding/discovery-and-execution-lifecycle',
                'agentic-systems/skill/coding/skills-tools-mcp-relationship',
                'agentic-systems/skill/coding/tool-definitions-and-instructions-engineering',
                'agentic-systems/skill/coding/repository-context-engineering',
                'agentic-systems/skill/coding/vscode-devcontainers-integration',
                'agentic-systems/skill/coding/mcp-integration-and-memory',
                'agentic-systems/skill/coding/multi-agent-and-observability',
                'agentic-systems/skill/coding/governance-and-security',
                'agentic-systems/skill/coding/evaluation-reusability-deduplication',
                'agentic-systems/skill/coding/enterprise-workflows-comparative-analysis-and-patterns',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Configuration',
          items: [
            'agentic-systems/config/index',
            'agentic-systems/config/enterprise-agentic-ai-config-management-2026',
          ],
        },
        {
          type: 'category',
          label: 'Harness',
          items: [
            'agentic-systems/harness/index',
            'agentic-systems/harness/Harness_Engineering_Research_Report',
            'agentic-systems/harness/Harness_Engineering_AI_Agents_and_Vendor_Landscape',
            'agentic-systems/harness/Harness_BestPractices_AntiPatterns_Roadmap',
            'agentic-systems/harness/Harness_Security_SupplyChain_Observability',
            'agentic-systems/harness/Harness_Interview_Question_Bank',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Agentic UI & Applications',
      items: [
        'agentic-ui/index',
        'agentic-ui/evolution-human-ai-interfaces',
        'agentic-ui/agui-standards-landscape',
        'agentic-ui/enterprise-reference-architecture',
        'agentic-ui/application-lifecycle',
        'agentic-ui/reliability-engineering',
        'agentic-ui/scalability-engineering',
        'agentic-ui/performance-engineering',
        'agentic-ui/security-architecture',
        'agentic-ui/context-engineering',
        'agentic-ui/agent-ux-patterns',
        'agentic-ui/governance',
        'agentic-ui/responsible-ai',
        'agentic-ui/evaluation-framework',
        'agentic-ui/observability',
        'agentic-ui/devsecops',
        'agentic-ui/anti-patterns',
        'agentic-ui/industry-reference-architectures',
        'agentic-ui/decision-frameworks',
        'agentic-ui/future-outlook',
        'agentic-ui/identity-auth-architecture',
      ],
    },
    {
      type: 'category',
      label: 'AI Development',
      items: [
        'ai-development/index',
        {
          type: 'category',
          label: 'AIDLC',
          items: [
            'ai-development/aidlc/index',
            'ai-development/aidlc/AIDLC_Enterprise_Framework_2025',
            'ai-development/aidlc/EA_AIDLC_Deep_Research_2026',
            'ai-development/aidlc/AIDLC_Agile_CICD_AI_Transformation_2026',
            'ai-development/aidlc/Agile_in_the_Age_of_Agentic_AI_2026',
            'ai-development/aidlc/AIDLC_Artifact_Reference_Library',
            'ai-development/aidlc/EA_Lifecycle_Artifact_Templates_2026',
          ],
        },
        {
          type: 'category',
          label: 'Testing & Evaluation',
          items: [
            'ai-development/testing/index',
            'ai-development/testing/AI_Agent_Evaluation_Framework_Guide',
            'ai-development/testing/AI_Agent_Evaluation_Framework_Complete',
            'ai-development/testing/Agent_Testing_Monitoring_Evaluation',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'AI Economics',
      items: [
        'ai-economics/index',
        'ai-economics/ai-value-creators-synthesis',
        'ai-economics/ai-coding-agents-2026',
        'ai-economics/AI-Value-Creator-Deliverables-Pack',
        'ai-economics/Agentic-AI-Use-Case-Value-Lifecycle',
        'ai-economics/AI_Cost_Implementation_Guide_2026',
      ],
    },
    {
      type: 'category',
      label: 'AI Foundations',
      items: [
        'ai-foundations/index',
        'ai-foundations/AI_Native_Architecture_Evolution_Report',
        {
          type: 'category',
          label: 'Agentic AI Landing Zone (Complete Platform)',
          items: [
            'ai-foundations/agentic_ai_landing_zone_architecture',
            'ai-foundations/agentic_ai_landing_zone_business_layer',
            'ai-foundations/agentic_ai_landing_zone_eu_ai_act',
            'ai-foundations/agentic_ai_landing_zone_playbooks',
            'ai-foundations/agentic_ai_landing_zone_platform_layer',
            'ai-foundations/agentic_ai_landing_zone_context_engineering',
            'ai-foundations/agentic_ai_landing_zone_evaluation',
            'ai-foundations/agentic_ai_landing_zone_multiagent',
            'ai-foundations/agentic_ai_landing_zone_visual_guide',
            'ai-foundations/agentic_ai_landing_zone_memory_architecture',
            'ai-foundations/agentic_ai_landing_zone_tier3_complete',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'AI Protocols',
      items: [
        'ai-protocols/index',
        {
          type: 'category',
          label: 'Auth & Identity',
          items: [
            'ai-protocols/auth/index',
            'ai-protocols/auth/entra-3lo-agent-auth-standards-architecture',
            'ai-protocols/auth/entra-3lo-agent-auth-implementation',
            'ai-protocols/auth/entra-3lo-agent-auth-security-review',
            'ai-protocols/auth/entra-3lo-agent-auth-multiagent-compliance',
            'ai-protocols/auth/tool-authentication-connectors',
            'ai-protocols/auth/agent-identity-entra-vs-awsagentcore',
            'ai-protocols/auth/Part3_Identity_OBO_Sessions',
            'ai-protocols/auth/auth_identity_flows',
            'ai-protocols/auth/enterprise-ai-platform-auth-survey',
            'ai-protocols/auth/marketplace-connector-auth-patterns',
            'ai-protocols/auth/auth-standards-reference',
          ],
        },
        {
          type: 'category',
          label: 'Protocol Standards',
          items: [
            'ai-protocols/standards/index',
            'ai-protocols/standards/AI_Protocols_Standards_Service_Industry_Guide_2026',
          ],
        },
        {
          type: 'category',
          label: 'MCP',
          items: [
            'ai-protocols/mcp/index',
            'ai-protocols/mcp/MCP_Deep_Research_2026',
            'ai-protocols/mcp/MCP_Harness_AIDLC',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Cloud Platforms',
      items: [
        'cloud-platforms/index',
        {
          type: 'category',
          label: 'AWS AgentCore',
          items: [
            'cloud-platforms/aws/index',
            'cloud-platforms/aws/bedrock-agentcore-code-interpreter-architecture',
            'cloud-platforms/aws/agentcore_strands_deep_research_report',
            'cloud-platforms/aws/AWS_Native_Standards_First_Agentic_Architecture',
            'cloud-platforms/aws/AWS_Strands_AgentCore_AdvancedPatterns_v3',
            'cloud-platforms/aws/AWS_Strands_AgentCore_Builder_Journey_Kit',
            'cloud-platforms/aws/AWS_Strands_AgentCore_Delta_Supplement_v2',
            'cloud-platforms/aws/AgentCore_Memory_Architecture_Guide',
            'cloud-platforms/aws/AgentCore_Memory_Gaps_Extensions_2026',
            'cloud-platforms/aws/AgentCore_Memory_Operations_DeepDive',
          ],
        },
        'cloud-platforms/azure/index',
        {
          type: 'category',
          label: 'AI Gateway',
          items: [
            'cloud-platforms/ai-gateway/index',
            'cloud-platforms/ai-gateway/kong-ai-gateway-guide',
            'cloud-platforms/ai-gateway/kong-entra-id-integration',
            'cloud-platforms/ai-gateway/AI_Gateway_Full_Comparison',
            'cloud-platforms/ai-gateway/AI_Gateway_MultiTenant_MultiCloud',
            'cloud-platforms/ai-gateway/Enterprise_AI_Gateway',
          ],
        },
        {
          type: 'category',
          label: 'Kubernetes',
          items: [
            'cloud-platforms/kubernetes/index',
            'cloud-platforms/kubernetes/K8s_Handbook_Part1_Infrastructure_Evolution',
            'cloud-platforms/kubernetes/K8s_Handbook_Part2_Linux_Foundations',
            'cloud-platforms/kubernetes/K8s_Handbook_Part3_Containers',
            'cloud-platforms/kubernetes/K8s_Handbook_Part4_Kubernetes_Internals',
            'cloud-platforms/kubernetes/K8s_Handbook_Part5_Kubernetes_Resources',
            'cloud-platforms/kubernetes/K8s_Handbook_Part6_Kubernetes_Networking',
            'cloud-platforms/kubernetes/K8s_Handbook_Part7_Storage',
            'cloud-platforms/kubernetes/K8s_Handbook_Part8_Security',
            'cloud-platforms/kubernetes/K8s_Handbook_Part9_Platform_Engineering',
            'cloud-platforms/kubernetes/K8s_Handbook_Part10_Observability',
            'cloud-platforms/kubernetes/K8s_Handbook_Part11_AI_Infrastructure',
            'cloud-platforms/kubernetes/K8s_Handbook_Part12_Agentic_AI',
            'cloud-platforms/kubernetes/K8s_Handbook_Part13_Emerging_Standards',
            'cloud-platforms/kubernetes/K8s_Handbook_Part14_Reference_Architectures',
            'cloud-platforms/kubernetes/K8s_Handbook_Part15_Implementation_Labs',
            'cloud-platforms/kubernetes/K8s_Handbook_Part16_Future_Outlook',
          ],
        },
        {
          type: 'category',
          label: 'Infrastructure as Code',
          items: [
            'cloud-platforms/iac/index',
            {
              type: 'category',
              label: 'Terraform',
              items: [
                'cloud-platforms/iac/terraform/index',
                'cloud-platforms/iac/terraform/terraform-mastery-guide',
                'cloud-platforms/iac/terraform/ai-assisted-iac-mastery',
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Coding Tools',
      items: [
        'coding-tools/index',
        {
          type: 'category',
          label: 'Claude',
          items: [
            'coding-tools/claude/index',
            'coding-tools/claude/claude-models-2026',
            'coding-tools/claude/claude-api-mastery',
            'coding-tools/claude/claude-code-complete-2026',
            'coding-tools/claude/claude-agent-sdk-production',
            'coding-tools/claude/prompt-engineering-claude-4',
            'coding-tools/claude/claude-enterprise-2026',
            'coding-tools/claude/constitutional-ai-safety-2026',
            'coding-tools/claude/mcp-deep-guide',
            'coding-tools/claude/ccaf-exam-prep-complete',
            'coding-tools/claude/ruflo-agentic-ai-guide',
            'coding-tools/claude/claude-best-practices',
            'coding-tools/claude/claude_agents_best_practices_v2',
            'coding-tools/claude/Claude_Ecosystem_Research_Report',
            'coding-tools/claude/Anthropic_Partner_Cert_Study_Guide',
            'coding-tools/claude/CCAF_Study_Guide',
            'coding-tools/claude/CCAF_Advanced_Supplement',
            'coding-tools/claude/Module_1_Claude_Foundations',
            'coding-tools/claude/Module_3_Prompt_Engineering',
            'coding-tools/claude/Module_4_MCP',
            'coding-tools/claude/Module_5_Claude_Code_Agents',
            'coding-tools/claude/Module_6_Claude_Workflows',
            'coding-tools/claude/Module_7_Safety_Enterprise_Exam',
          ],
        },
        {
          type: 'category',
          label: 'GitHub Copilot',
          items: [
            'coding-tools/github-copilot/index',
            'coding-tools/github-copilot/github-copilot-zero-to-hero',
            'coding-tools/github-copilot/git-github-platform-engineering-handbook',
            'coding-tools/github-copilot/copilot-enterprise-playbook',
            'coding-tools/github-copilot/github-copilot-big-wins-research',
            'coding-tools/github-copilot/GitHub_Copilot_Enterprise_Research_2026',
            'coding-tools/github-copilot/Part01_Git_Internals',
            'coding-tools/github-copilot/Part01_Vision_Copilot_Architecture_RepoIntelligence',
            'coding-tools/github-copilot/Part02_GitHub_Architecture_and_Actions',
            'coding-tools/github-copilot/Part04_RAG_Agents_Models_Platform',
            'coding-tools/github-copilot/Part04_Runners_and_Runtime',
            'coding-tools/github-copilot/Part06_Marketplace_Pages_Packages',
            'coding-tools/github-copilot/Part07_Prompts_Evaluation_Spark_Infrastructure',
            'coding-tools/github-copilot/Part11_CICD_Secrets_Security',
            'coding-tools/github-copilot/Part11_Security_Governance',
            'coding-tools/github-copilot/Part13_CICD_Observability_Scaling',
            'coding-tools/github-copilot/Part14_Enterprise_APIs_Apps_CLI',
            'coding-tools/github-copilot/Part16_Artifacts_ReferenceArchitecture',
            'coding-tools/github-copilot/Part18_Ecosystem_Patterns_Labs',
          ],
        },
        {
          type: 'category',
          label: 'Code Review',
          items: [
            'coding-tools/code-review/index',
            'coding-tools/code-review/PR_Review_Handbook_Vol1_Traditional_Review',
            'coding-tools/code-review/PR_Review_Handbook_Vol2_Deep_Domain_Reviews',
            'coding-tools/code-review/PR_Review_Handbook_Vol3_AI_Assisted_Review',
            'coding-tools/code-review/PR_Review_Handbook_Vol4_Agentic_Review_Architecture',
            'coding-tools/code-review/PR_Review_Handbook_Vol5_Case_Studies_Maturity_Model',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Cyber Security Architecture',
      items: [
        'cybersec-architect/index',
        'cybersec-architect/evolution',
        'cybersec-architect/enterprise-security-architecture',
        'cybersec-architect/security-domains',
        'cybersec-architect/ai-security',
        'cybersec-architect/agentic-ai-security',
        'cybersec-architect/identity-architecture',
        'cybersec-architect/cloud-security',
        'cybersec-architect/ai-governance',
        'cybersec-architect/security-operations',
        'cybersec-architect/technology-investment',
        'cybersec-architect/ai-investment',
        'cybersec-architect/ea-deliverables',
        'cybersec-architect/security-patterns',
        'cybersec-architect/case-studies',
        'cybersec-architect/emerging-trends',
        'cybersec-architect/usecase-transcript',
      ],
    },
    {
      type: 'category',
      label: 'EA Masterclass',
      items: [
        'ea-masterclass/index',
        'ea-masterclass/module-01-ea-foundations/index',
        'ea-masterclass/module-02-business-acumen/index',
        'ea-masterclass/module-03-proposal-lifecycle/index',
        'ea-masterclass/module-04-technology-investment/index',
        'ea-masterclass/module-05-ai-investment-strategy/index',
        'ea-masterclass/module-06-business-case/index',
        'ea-masterclass/module-07-proposal-writing/index',
        'ea-masterclass/module-08-financial-literacy/index',
        'ea-masterclass/module-09-enterprise-ai-architecture/index',
        'ea-masterclass/module-10-governance/index',
        'ea-masterclass/module-11-executive-communication/index',
        'ea-masterclass/module-12-ai-consulting/index',
        {
          type: 'category',
          label: 'Module 13: Case Studies',
          items: [
            'ea-masterclass/module-13-case-studies/index',
            'ea-masterclass/module-13-case-studies/global-bank',
            'ea-masterclass/module-13-case-studies/healthcare',
            'ea-masterclass/module-13-case-studies/manufacturing',
            'ea-masterclass/module-13-case-studies/retail',
            'ea-masterclass/module-13-case-studies/government',
            'ea-masterclass/module-13-case-studies/telecom',
          ],
        },
        'ea-masterclass/module-14-mentoring/index',
        {
          type: 'category',
          label: 'Module 15: Distinguished Architect',
          items: [
            'ea-masterclass/module-15-distinguished-architect/index',
            'ea-masterclass/module-15-distinguished-architect/architecture-leadership',
            'ea-masterclass/module-15-distinguished-architect/executive-presence',
            'ea-masterclass/module-15-distinguished-architect/strategic-thinking',
            'ea-masterclass/module-15-distinguished-architect/fortune100-modernisation',
          ],
        },
        {
          type: 'category',
          label: 'Deliverables',
          items: [
            'ea-masterclass/deliverables/index',
            'ea-masterclass/deliverables/business-case-templates',
            'ea-masterclass/deliverables/consulting-templates',
            'ea-masterclass/deliverables/governance-templates',
          ],
        },
        {
          type: 'category',
          label: 'Workshop Transcripts',
          items: [
            'ea-masterclass/transcripts/index',
            'ea-masterclass/transcripts/bank-discovery-workshop',
            'ea-masterclass/transcripts/healthcare-executive-presentation',
            'ea-masterclass/transcripts/manufacturing-arb-review',
            'ea-masterclass/transcripts/retail-proposal-negotiation',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Enterprise Architecture',
      items: [
        'enterprise-architecture/index',
        {
          type: 'category',
          label: 'Strategy',
          items: [
            'enterprise-architecture/strategy/index',
            'enterprise-architecture/strategy/EA_Strategy_Playbook',
            'enterprise-architecture/strategy/Enterprise_AI_Strategic_Brief_2026',
            'enterprise-architecture/strategy/Enterprise_AI_Transformation_Blueprint_CTO_Guide_2026',
            'enterprise-architecture/strategy/AI_Cost_Implementation_Guide_2026',
            'enterprise-architecture/strategy/EA_AI_First_Transformation_Transcript',
          ],
        },
        {
          type: 'category',
          label: 'Frameworks',
          items: [
            'enterprise-architecture/framework/index',
            'enterprise-architecture/framework/Enterprise_AI_Architect_Communication_Guide',
            'enterprise-architecture/framework/Executive_Communication_Framework_Guide',
            'enterprise-architecture/framework/EA_Soft_Skills_Interview_Master_Guide',
          ],
        },
        {
          type: 'category',
          label: 'Processes',
          items: [
            'enterprise-architecture/process/index',
            'enterprise-architecture/process/enterprise-technology-selection-framework',
            'enterprise-architecture/process/ai-solution-lifecycle-deliverables',
            'enterprise-architecture/process/Enterprise_AI_Architect_Bible_2026',
            'enterprise-architecture/process/Enterprise_AI_Architect_Deep_Dive_Guide',
            'enterprise-architecture/process/Enterprise_Agentic_AI_Architecture_Playbook_2026',
            'enterprise-architecture/process/EA_Lifecycle_Artifact_Templates_2026',
            'enterprise-architecture/process/EA_Lifecycle_Checklist',
            'enterprise-architecture/process/EA_Mastery_Guide',
            'enterprise-architecture/process/EA_Real_Life_Transcript',
          ],
        },
        {
          type: 'category',
          label: 'Best Practices',
          items: [
            'enterprise-architecture/best-practices/index',
            'enterprise-architecture/best-practices/EA_BestPractices_Jargon',
            'enterprise-architecture/best-practices/EA_Glossary_CheatSheet',
          ],
        },
        {
          type: 'category',
          label: 'ARB',
          items: [
            'enterprise-architecture/architectural-review-board/index',
            'enterprise-architecture/architectural-review-board/Volume1_Governance_Ecosystem_Operating_Models',
            'enterprise-architecture/architectural-review-board/Volume2_Economics_Decision_Science',
            'enterprise-architecture/architectural-review-board/Volume3_Knowledge_Management_Capability_Mapping',
            'enterprise-architecture/architectural-review-board/Volume4_Artifact_Catalog_Quality_Attributes',
            'enterprise-architecture/architectural-review-board/Volume5_Review_Questions_Scorecards',
            'enterprise-architecture/architectural-review-board/Volume6_Banking_Industry_DeepDive',
            'enterprise-architecture/architectural-review-board/Volume7_AI_Native_ARB_Case_Studies',
            'enterprise-architecture/architectural-review-board/Volume8_Implementation_Accelerator_Kit',
            'enterprise-architecture/architectural-review-board/Volume9_Enterprise_Reference_Repository',
            'enterprise-architecture/architectural-review-board/Volume10_Collaborative_Use_Case_Transcripts',
          ],
        },
        {
          type: 'category',
          label: 'Specialization',
          items: [
            'enterprise-architecture/specialization/index',
            'enterprise-architecture/specialization/APEX_EA_Final',
            'enterprise-architecture/specialization/DSA_Principal_Architect_Reference',
            'enterprise-architecture/specialization/Principal_Enterprise_AI_Guide_Educative',
            'enterprise-architecture/specialization/AI_Transformation_Consultant_Toolkit_2026',
            'enterprise-architecture/specialization/Enterprise_Data_Architect_AI_GenAI',
            'enterprise-architecture/specialization/Enterprise_Manager_AI_GenAI',
            'enterprise-architecture/specialization/EA_OKR_KPI_Research',
            'enterprise-architecture/specialization/EA_Business_Communication_Executive_Skills',
            'enterprise-architecture/specialization/AI_Invoice_Auditor_Architecture_v5',
            'enterprise-architecture/specialization/RFI_AI_Platform_Transcript',
          ],
        },
        {
          type: 'category',
          label: 'AI Architecture',
          items: [
            'enterprise-architecture/ai-architecture/index',
            'enterprise-architecture/ai-architecture/enterprise-ai-architect-foundations',
            'enterprise-architecture/ai-architecture/enterprise-multi-model-ai-strategy',
            'enterprise-architecture/ai-architecture/enterprise-ai-architecture-patterns',
            'enterprise-architecture/ai-architecture/enterprise-ai-governance-compliance',
            'enterprise-architecture/ai-architecture/enterprise-ai-skills-assessment',
            'enterprise-architecture/ai-architecture/agentic-ai-security-identity',
            'enterprise-architecture/ai-architecture/agent-interoperability-orchestration',
            'enterprise-architecture/ai-architecture/machine-readable-ea',
            'enterprise-architecture/ai-architecture/agentic-ai-security-guardrails',
            'enterprise-architecture/ai-architecture/agentic-ai-reliability-observability-governance',
            'enterprise-architecture/ai-architecture/agent-reliability-engineering',
            'enterprise-architecture/ai-architecture/enterprise-aiops-guide',
            'enterprise-architecture/ai-architecture/ai-harness-architecture-orchestration',
            'enterprise-architecture/ai-architecture/mcp-a2a-protocol-deep-dive',
            'enterprise-architecture/ai-architecture/agent-memory-planning-architecture',
            'enterprise-architecture/ai-architecture/agent-communication-identity-gateway',
            'enterprise-architecture/ai-architecture/enterprise-agent-reference-architectures',
          ],
        },
        {
          type: 'category',
          label: 'Transformation',
          items: [
            'enterprise-architecture/transformation/index',
            'enterprise-architecture/transformation/ai-first-to-ai-native',
            'enterprise-architecture/transformation/Executive_Summary_and_AI_Vision',
            'enterprise-architecture/transformation/Current_State_Assessment_and_AI_Maturity',
            'enterprise-architecture/transformation/AI_Opportunity_Portfolio',
            'enterprise-architecture/transformation/Enterprise_AI_Platform_and_Data_Architecture',
            'enterprise-architecture/transformation/Governance_Responsible_AI_and_Security',
            'enterprise-architecture/transformation/Target_Operating_Model_and_Change',
            'enterprise-architecture/transformation/Roadmap_Financials_KPIs_and_Risk',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Interview Prep',
      items: [
        'interview-prep/index',
        {
          type: 'category',
          label: 'EA Interviews',
          items: [
            'interview-prep/ea/index',
            'interview-prep/ea/EA_Interview_Handbook',
            'interview-prep/ea/EA_Interview_Handbook_DELTA',
            'interview-prep/ea/EA_Interview_Master_Guide',
            'interview-prep/ea/EA_Interview_Vol3_CTO_AI',
          ],
        },
        'interview-prep/Enterprise_Architect_in_the_Age_of_AI',
        'interview-prep/ea-ai-artifacts-and-metrics',
        'interview-prep/EA_Soft_Skills_and_Behaviors',
        'interview-prep/EA_Senior_Interview_Questions',
        'interview-prep/EA_Quality_Resilience_Testing_Interview_Questions',
        'interview-prep/EA_HITL_HOTL_HOOL_Interview_Questions',
        'interview-prep/AI_Agent_Systems_Interview_Guide',
        'interview-prep/AI_Engineer_Question_Bank',
        'interview-prep/Agentic_AI_Platforms_Questionnaire_2025',
        'interview-prep/EY_AI_Architect_Interview_Guide_1',
        'interview-prep/Enterprise_GenAI_Architect_Interview_Guide',
        'interview-prep/Hard_Scenarios_Interview_Prep',
        'interview-prep/ML_AI_Interview_Mastery_Guide',
      ],
    },
    {
      type: 'category',
      label: 'Knowledge',
      items: [
        'knowledge-engineering/index',
        {
          type: 'category',
          label: 'Data Architecture',
          items: [
            'knowledge-engineering/data/index',
            'knowledge-engineering/data/Data_Architecture_for_AI_Report',
            'knowledge-engineering/data/End_to_End_Lineage_Systems_Report',
            'knowledge-engineering/data/Enterprise_Data_Systems_AI_Governance_Report',
          ],
        },
        {
          type: 'category',
          label: 'Knowledge & RAG',
          items: [
            'knowledge-engineering/knowledge/index',
            'knowledge-engineering/knowledge/Enterprise_Knowledge_Architectures_Report',
            'knowledge-engineering/knowledge/Complex_RAG_Deep_Dive',
            'knowledge-engineering/knowledge/Autonomous_Knowledge_Engineering_System',
          ],
        },
        {
          type: 'category',
          label: 'Industry Knowledge Systems',
          items: [
            'knowledge-engineering/industry-practices/index',
            'knowledge-engineering/industry-practices/tech-companies',
            'knowledge-engineering/industry-practices/consulting-firms',
            'knowledge-engineering/industry-practices/governance-rai',
            'knowledge-engineering/industry-practices/grounding',
            'knowledge-engineering/industry-practices/evaluation',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Quantum AI',
      link: {type: 'doc', id: 'quantum/index'},
      items: [
        {type: 'doc', id: 'quantum/zero-to-mastery', label: 'Zero to Mastery'},
        {type: 'doc', id: 'quantum/IBM_Associate_Quantum_CertGuide', label: 'IBM Associate Cert Guide'},
        {type: 'doc', id: 'quantum/IBM_Developer_Quantum_CertGuide', label: 'IBM Developer Cert Guide'},
        {type: 'doc', id: 'quantum/Quantum_AI_TechGiants_Report', label: 'Tech Giants Report'},
        {type: 'doc', id: 'quantum/Quantum_AI_Startups_Report', label: 'Startups Report'},
        {type: 'doc', id: 'quantum/Quantum_AI_Consultancies_Report', label: 'Consultancies Report'},
      ],
    },
    {
      type: 'category',
      label: 'Security',
      items: [
        'ai-security-governance/index',
        {
          type: 'category',
          label: 'AI Security',
          items: [
            'ai-security-governance/security/index',
            'ai-security-governance/security/Foundations-Reference-Architecture',
            'ai-security-governance/security/Identity-MCP-A2A-Security-Blueprint',
            'ai-security-governance/security/Part4_Runtime_Security_Governance',
            'ai-security-governance/security/AI-SOC-Observability-RedTeam-Memory',
            'ai-security-governance/security/Economic-Security-FinOps-Commerce-PQC',
            'ai-security-governance/security/Operating-Model-Maturity-Roadmap',
            'ai-security-governance/security/Zero-to-Mastery-Curriculum',
            'ai-security-governance/security/Architects-Field-Guide',
          ],
        },
        'ai-security-governance/deep-mind/index',
        'ai-security-governance/policy/index',
      ],
    },
    {
      type: 'category',
      label: 'Soft Skills',
      items: [
        'soft-skills/index',
        'soft-skills/CTO_Voice_Mastery_Program',
        'soft-skills/Mental_Models_for_Voice_Training',
        'soft-skills/Storytelling_Exercise_Workbook',
        'soft-skills/Voice_Training_30Day_Plan',
      ],
    },
    {
      type: 'category',
      label: 'Sovereign & Constitutional AI',
      items: [
        'sovereign-constitutional-ai/index',
        'sovereign-constitutional-ai/sovereign-ai-foundations',
        'sovereign-constitutional-ai/constitutional-ai-engineering',
        'sovereign-constitutional-ai/rai-operating-model',
        'sovereign-constitutional-ai/ai-alignment-control',
        'sovereign-constitutional-ai/ai-governance-operating-model',
        'sovereign-constitutional-ai/ai-risk-taxonomy',
        'sovereign-constitutional-ai/ai-safety-framework',
        'sovereign-constitutional-ai/ai-assurance-audit-architecture',
        'sovereign-constitutional-ai/constitutional-agent-architecture',
        'sovereign-constitutional-ai/policy-as-code-framework',
        'sovereign-constitutional-ai/democratic-ai-public-interest',
        'sovereign-constitutional-ai/sovereign-ai-roadmap-maturity',
      ],
    },
    {
      type: 'category',
      label: 'Use Cases',
      items: [
        'ai-usecases/index',
        'ai-usecases/EU_Banking_AI_Evaluation_Compliance_Guide',
        {
          type: 'category',
          label: 'EU Bank AI Copilot',
          items: [
            'ai-usecases/eu-bank-ai-copilot-complete',
            'ai-usecases/eu-bank-ai-copilot-architecture',
            'ai-usecases/eu-bank-sequence-diagrams',
          ],
        },
        'ai-usecases/airgapped-banking-architecture',
        'ai-usecases/CEO_Agent_Solution_Blueprint',
        'ai-usecases/CEO_Agent_Failure_Modes_Governance_Harness',
        'ai-usecases/ceo_agent_pitch',
        'ai-usecases/Mental_Model_Encyclopedia',
        'ai-usecases/Strategic_Thinking_Handbook',
        'ai-usecases/Enterprise_AI_Case_Studies',
        'ai-usecases/Part6_Banking_Case_Study',
        {
          type: 'category',
          label: 'Industry Verticals',
          items: [
            'ai-usecases/aviation',
            'ai-usecases/banking',
            'ai-usecases/healthcare',
            'ai-usecases/manufacturing',
            'ai-usecases/telecom',
            'ai-usecases/government',
            'ai-usecases/pharma',
            'ai-usecases/energy',
            'ai-usecases/logistics',
            'ai-usecases/media',
          ],
        },
        {
          type: 'category',
          label: 'Agentic Case Studies',
          items: [
            'ai-usecases/Case_01_Meridian_Fraud_Investigation_Agents',
            'ai-usecases/Case_02_Cascadia_Prior_Authorization_Agent',
            'ai-usecases/Case_03_Ironclad_Maintenance_Orchestration_Agent',
            'ai-usecases/Case_04_Northline_Customer_Service_Agents',
            'ai-usecases/Case_05_Aurelia_Research_Assistant_Agent',
            'ai-usecases/Case_06_Skyline_Disruption_Control_Tower',
            'ai-usecases/Case_07_Harborstone_Claims_Processing_Agents',
            'ai-usecases/Case_08_Sterling_Loan_Underwriting_Agent',
            'ai-usecases/Case_09_Palisade_Grid_Operations_Agent',
            'ai-usecases/Case_10_Vantara_Procurement_Negotiation_Agents',
            'ai-usecases/Case_11_Vaxion_Clinical_Trial_Matching_Agent',
            'ai-usecases/Case_12_Meritage_Dynamic_Pricing_Agent',
            'ai-usecases/Case_13_StateDHS_Benefits_Navigation_Agent',
            'ai-usecases/Case_14_Falkirk_SOC_Threat_Response_Agent',
            'ai-usecases/Case_15_Correlate_Recruiting_Screening_Agent',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Workflow Orchestration',
      items: [
        'workflow-orchestration/index',
        'workflow-orchestration/executive-summary',
        'workflow-orchestration/evolution-timeline',
        'workflow-orchestration/workflow-vs-agent-architecture',
        'workflow-orchestration/durable-vs-cognitive-execution',
        'workflow-orchestration/temporal-deep-dive',
        'workflow-orchestration/camunda-deep-dive',
        'workflow-orchestration/ai-coding-orchestrators',
        'workflow-orchestration/agent-frameworks-comparison',
        'workflow-orchestration/tool-calling-orchestration',
        'workflow-orchestration/mcp-impact',
        'workflow-orchestration/a2a-orchestration-patterns',
        'workflow-orchestration/ai-planning-vs-workflow-engines',
        'workflow-orchestration/human-in-the-loop-architectures',
        'workflow-orchestration/memory-vs-workflow-state',
        'workflow-orchestration/reliability-playbook',
        'workflow-orchestration/observability-framework',
        'workflow-orchestration/security-architecture',
        'workflow-orchestration/enterprise-governance-model',
        'workflow-orchestration/reference-architectures',
        'workflow-orchestration/decision-matrix',
        'workflow-orchestration/anti-patterns-catalog',
        'workflow-orchestration/capability-maturity-model',
        'workflow-orchestration/future-predictions',
      ],
    },
    {type: 'doc', id: 'about', label: 'About'},
  ],
};

module.exports = sidebars;
